### ISSUE TITLE
Sample XML request for a Credit Card on Express

### ISSUE THREAD

**Issue by dharmnathdubal** [ElementPS/Express.CSharp#1] opened 2018-07-06 09:48 UTC
I got an error when I passing sample XML request to 'https://certtransaction.elementexpress.com/' url
Can anyone specify on it why getting an error.
Please find below attachment
![image](https://user-images.githubusercontent.com/10347470/42372236-57235b30-812f-11e8-8272-0079c27b51bc.png)

**Comment by dourada** [comment] 2018-07-06 16:06
Greetings, the issue is that legacy ciphers have been removed from the cert platform and only tls 1.2 is supported.  I checked in a change that forces tls 1.2 which allows the transaction to proceed but there are likely more elegant ways to resolve this issue like using one of the later .net versions that default to tls 1.2 but I was not sure if you are able to leverage a later .net version.

**Closed as completed by dourada** 2018-07-06 16:06 UTC
